# -*- coding: utf-8 -*-
"""PANDAS_CC_D2_Cleslley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121WHzsrNvIHRccEYq6F0x8Tg9xpK8SHP

***MANIPULAÇÃO DE DADOS COM PANDAS - ESTRUTURA DE DADOS COM LISTA, TUPLA E DICIONÁRIO***

`*Documentação disponível em:* https://pandas.pydata.org/docs/`
"""

import pandas as pd # importa a biblioteca 'Pandas'.
#                     Uma das estruturas de dados mais utilizadas no pandas é o DataFrame.
#                     Uma instância do tipo DataFrame é um pbjeto de duas (ou mais) dimensões com as seguintes características:
#                  -- Suas dimensões podem ser modificadas decorrente da modificação dos dados.
#                  -- Seus dados podem ser acessados através de rótulos ao invés de exclusivamente por índices.
#                  -- É também possível trabalhar com dados heterogêneos, tanto nas linhas como também nas colunas.

# Criando um DataFrame a partir de uma lista de tuplas:

nomes = ['Cleslley', 'Gabriel', 'Victor']
idades = [20, 21, 20]
dados = list(zip(nomes, idades)) # transforma as duas listas em tupla
print(dados)
df = pd.DataFrame(data = dados) # ---> comando do pandas
print(df)

#dados = classe // nome, idades = objetos

# Criando DataFrames a partir de um Dicionário:

import pandas as pd
dicionario = { 'Identificação' : ['Guilherme', 'Gabriel A', 'Gabriel V', 'Cleslley', 'Lara', 'César'],
               'Idade' : [23, 21, 21, 20, 20, 19]
             }
df = pd.DataFrame(data=dicionario)
print(df)

import pandas as pd
dados = [('Aliciyi', 19), ('Bianca', 20), ('Carluxo', 27)]
colunas = ['Nome', 'Idade']
linhas = ['A', 'B', 'C']
df = pd.DataFrame(dados, columns = colunas, index = linhas)
print(df)

print(list(df.index))
print(list(df.columns))
print(df.ndim)
print(df.shape)
print(df.size)
print(df.empty)

df.columns = ['Identificação', 'Idade']
df.index = ['Linha1','Linha2','Linha3']

# Proposta de exercício de Data Frame: Dados de músicas de uma plataforma de streaming
import pandas as pd

nome_musicas = ["Roly-Poly", "Poster Child", "Exit Music (For A Film)", "Stormrazor", "Sea Of Problems", "Heavenly Key", "Hotel Room Service", "Billie Jeans", "Midas Touch", "Controllah", "festa estranha"]
artistas = ["T-ARA", "RHCP", "Radio Head", "Pentakill", "Glichery", "Glichery", "Pitibull", "Michael Jackson", "KIOF", "Gorillaz & MC Bin L", "Jumbu"]
genero = ["Pop", "Rock", "Alternative", "Rock", "Phonk", "Phonk", "Eletronic", "Pop", "Pop", "Alternative", "Alternative"]
ano_lancamento = [2011, 2022, 1997, 2021, 2023, 2023, 2009, 1983, 2024, 2023, 2023]
duracao_musica = [3.3, 5.1, 4.7, 4.0, 1.5, 2.5, 3.5, 4.5, 2.4, 2.3, 2.5]

dados_musicais = {
    'Música': nome_musicas,
    'Artista': artistas,
    'Gênero': genero,
    'Ano de lançamento': ano_lancamento,
    'Duração (segundos)' : duracao_musica,
}

musica_df = pd.DataFrame(dados_musicais)
print(musica_df)

# a) Mais ouvidas
print("a) Mais ouvidas: ")
mais_ouvida = musica_df.loc[musica_df['Ano de lançamento'].idxmax()]['Música']
print(mais_ouvida)
print()
# b) Artista com mais músicas
print("b) Artistas com mais músicas:")
artista_mais_musicas = musica_df['Artista'].mode()[0]
print(artista_mais_musicas)
print()
# c) Gênero mais ouvido
print("c) Gênero mais popular:")
genero_mais_popular = musica_df['Gênero'].mode()[0]
print(genero_mais_popular)
print()
# d) Música mais recente
print("d) Música mais recente:")
musica_mais_recente = musica_df.loc[musica_df['Ano de lançamento'].idxmax()]['Música']
print(musica_mais_recente)
print()
# e) Adicionar nova coluna com duração de segundos
print("e) Duração (segundos):")
musica_df['Duração (segundos)'] = musica_df['Duração (segundos)'] * 60
print(musica_df)
print()

#Proposta 2: Dados de Estudantes de uma Escola
#a) Média de Notas
#b) Aluno com maior nota em Estrutura de Dados
#c) Aluno mais novo
#d) Aluno com menor nota em Banco de Dados
#e) Adicionar uma nova coluna com a média geral das notas import pandas as pd

import pandas as pd

aluno = ["Printf", "SnakeGRTC", "Grimm", "ZeroBullets", "Lorditozito"]
nota1 = [9, 7, 5, 6, 6]
nota2 = [8, 6, 5, 9, 7]
data_nasc_aluno = [2003, 2003, 2002, 2004, 2000]

dados_alunos = {
    'Alunos' : aluno,
    '1ª nota' : nota1,
    '2ª nota' : nota2,
    'Idade' : data_nasc_aluno,
}

estudantes_df = pd.DataFrame(dados_alunos)
print(estudantes_df)
print()

#a) Média de Notas
print("a) Média de notas: ")
media_notas = (estudantes_df['1ª nota'] + estudantes_df['2ª nota']) / 2
print(media_notas)
print()

#b) Aluno com maior nota em Estrutura de Dados
print("b) Aluno com maior nota em Estrutura de Dados: ")
media_notas = (estudantes_df['1ª nota'] + estudantes_df['2ª nota']) / 2
print(media_notas)
print()
