# -*- coding: utf-8 -*-
"""exemplo_trab_pilhas_em_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnnT338qULnPaE1e1Ij42bhMVlf5eo3Q
"""

class Stack:
     def __init__(self):
         self.items = []

     def isEmpty(self):
         return self.items == []

     def push(self, item):
         self.items.append(item)

     def pop(self):
         return self.items.pop()

     def peek(self):
         return self.items[len(self.items)-1]

     def size(self):
         return len(self.items)

s=Stack()

print(s.isEmpty())
s.push(4)
s.push('dog')
print(s.peek())
s.push(True)
print(s.size())
print(s.isEmpty())
s.push(8.4)
print(s.pop())
print(s.pop())
print(s.size())