# -*- coding: utf-8 -*-
"""Avaliacao_A1_Cleslley_CC_07Jun24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dRz0SShy69iRjNdHhvKNm2I6jIEOdrR

# Nova seção

Nome: CLESLLEY DE MOURA LIMA

rgm: 32621272

Tema:

# **Regra 1**: UTILIZAR O ZEN DO PYTHON (Vale 1,0 na A1)

Disponívem em Português: https://edisciplinas.usp.br/pluginfile.php/6585696/mod_resource/content/1/Eric%20Matthes%20-%20Curso%20Intensivo%20de%20Python-Novatec%20%282016%29.pdf

Página
"""

#Regra 3: Complexo ou complicado?
#Faça um programa que informe o número de loops para um contador que imprima todos os números primos de 1 a 100.

import this

def primo(number):

#Verifica se o número é primo
    if number < 2:
        return False
#Contador = 'i'
    for contador in range(2, int(math.sqrt(number)) + 1):
      # range(2, int(math.sqrt(number)) + 1): Esta é uma função que cria um intervalo de números.
      # No caso, começa em 2 (pois os números primos são maiores que 1) e termina em int(math.sqrt(number)) + 1.
      # O int(math.sqrt(number)) calcula a raiz quadrada de number, e a função int() arredonda esse valor para o inteiro mais próximo.
      # Adicionamos 1 para garantir que o último número seja incluído no intervalo.
        if number % contador == 0:
            return False
    return True

def main():
#Imprime todos os números primos de 1 a 100.
    print("Os números primos de 1 a 100 são:")
    count = 0  #Contador de loops
    for num in range(1, 101):
        if primo(num):
            count += 1
            print(num)
    print(f"Número de loops: {count}")

if __name__ == "__main__":
    main()

#Utilizei o método FOR por ser mais rápido por que ele já tem mais velocidade pelo range.

#Exemplo da professora:

import this

for contador in range (1, 101):
  print(contador)

#Com Do While:

contador = 0;

while contador <= 100:
  print(contador)
  contador = contador + 1

contador = 1

while contador > 0 and contador < 11:
  print(contador)
  contador += 1

"""# Algorítimos de Busca"""

# O que é busca?
#Criar DatFrame bidimensional de Heliportos em Brasília com Pandas e Python

import pandas as pd

heliporto_nome = ["SBBR - Presidente Juscelino Kubitschek", "SSGP - Piquet", "SIQE - Planalto Central Brasília/DF", "SDCB - Centro Brasileiro de Aviação Agrícola Experimental e Recreativo (CBAAER"]
heliporto_endereco = ["Brasília/DF", "Brasília/DF", "Brasília/DF", "Brasília/DF"]

dados_heliporto = {
    'Nome do Heliporto' : heliporto_nome,
    'Endereço do Heliporto' : heliporto_endereco
}

heliportos_df = pd.DataFrame(dados_heliporto)
print(dados_heliporto)
print()
print(heliportos_df.shape)
display(heliportos_df)

"""**Exercício 1**:
Escreva um programa que leia uma sequência com N números reais e imprime a sequência eliminando os elementos repetidos. Esse exercício pode ser dividido em 2 partes:
"""
